#! /bin/sh

script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi 
done

bspc subscribe monitor_add | while read msg ; do
	bspc monitor eDP1 -d I II III IV V
	bspc monitor DP2 -d VI VII VIII IX X
	#notify-send $extern connected
	bspc config -m DP2 top_padding 27
	bspc config -m eDP1 top_padding 0 
	xsetwacom set "Wacom HID 5113 Pen stylus" MapToOutput eDP1
	xsetwacom set "Wacom HID 5113 Pen eraser" MapToOutput eDP1
	xsetwacom set "Wacom HID 5113 Finger touch" MapToOutput eDP1
done
